const metiers=
{
   "professeur": [
      "Professeur de mathématiques",
      "Professeur de français",
      "Professeur d'anglais",
      "Professeur de physique-chimie",
      "Professeur de sciences économiques et sociales",
      "Professeur d'histoire-géographie",
      "Professeur de sciences de la vie et de la terre",
      "Professeur de technologie",
      "Professeur d'informatique",
      "Professeur d'éducation physique et sportive",
      "Professeur d'arts plastiques",
      "Professeur de musique",
      "Professeur de langues étrangères",
      "Professeur de philosophie",
   "Professeur de sciences physiques",
   "Professeur de sciences de l'ingénieur",
   "Professeur de sciences médicales",
   "Professeur de sciences sociales",
   "Professeur de droit",
   "Professeur de gestion",
   "Professeur de psychologie",
   "Professeur de lettres arabes",
   "Professeur de langues et cultures amazighes",
   "Professeur de sciences islamiques",
   "Professeur de sciences économiques",
   "Professeur de comptabilité",
   "Professeur de marketing",
   "Professeur d'économie",
   "Professeur de biologie",
   "Professeur de géologie",
   "Professeur de chimie",
   "Professeur d'informatique appliquée",
   "Professeur de génie électrique",
   "Professeur de mécanique",
   "Professeur d'architecture",
   "Professeur de gestion des entreprises",
   "Professeur d'électronique",
   "Professeur de mathématiques appliquées",
   "Professeur de sciences de la terre",
   "Professeur d'énergétique",
   "Professeur de génie civil",
   "Professeur de génie mécanique",
   "Professeur de génie informatique",
   "Professeur de génie des procédés",
   "Professeur de génie industriel",
   "Professeur de management",
   "Professeur de communication",
   "Professeur de gestion hôtelière",
   "Professeur de tourisme",
   "Professeur de sciences politiques",
   "Professeur de journalisme",
   "Professeur de design",
   "Professeur de mode",
   "Professeur de restauration",
   "Professeur d'hôtellerie",
   "Professeur d'aviation",
   "Professeur de transport et logistique",
   "Professeur d'architecture d'intérieur",
   "Professeur de beaux-arts",
   "Professeur de cinéma et audiovisuel",
   "Professeur de théâtre",
   "Professeur de danse",
   "Professeur de yoga",
   "Professeur de méditation",
   "Professeur de coaching",
   "Professeur de développement personnel",
   "Professeur de langues étrangères",
   "Professeur de communication",
   "Professeur de leadership",
   "Professeur de marketing",
   "Professeur de vente",
   "Professeur de gestion de projet",
   "Professeur de gestion des ressources humaines",
   "Professeur de finances",
   "Professeur de comptabilité",
   "Professeur de développement web",
   "Professeur de programmation",
   "Professeur de design graphique",
   "Professeur de développement d'applications mobiles",
   "Professeur de cybersécurité",
   "Professeur de réseaux informatiques",
   "Professeur de génie logiciel",
   "Professeur de biochimie",
   "Professeur de microbiologie",
   "Professeur de biologie moléculaire",
   "Professeur de physiologie",
   "Professeur de génétique",
   "Professeur de sciences humaines",
   "Professeur de psychologie",
   "Professeur de sociologie",
   "Professeur de sciences politiques",
   "Professeur de géographie humaine",
   "Professeur de sciences de l'éducation",
   "Professeur de sciences de la communication",
   "Professeur de littérature",
   "Professeur de philosophie",
   "Professeur d'histoire",
   "Professeur d'archéologie",
   "Professeur de linguistique",
   "Professeur d'anthropologie",
   "Professeur de musicologie",
   "Professeur d'arts visuels",
   "Professeur de cinéma",
   "Professeur de théâtre",
   "Professeur de danse",
   "Professeur de musique",
   "Professeur d'arts plastiques",
   "Professeur d'arts du spectacle",
   "Professeur de beaux-arts",
   "Professeur d'arts martiaux",
   "Professeur de yoga",
   "Professeur de fitness",
   "Professeur de nutrition",
   "Professeur de diététique",
   "Professeur de médecine",
   "Professeur de chirurgie",
   "Professeur de cardiologie",
   "Professeur de pédiatrie",
   "Professeur de dermatologie",
   "Professeur de gynécologie",
   "Professeur de neurologie",
   "Professeur de psychiatrie",
   "Professeur de pharmacologie",
   "Professeur de santé publique",
   "Professeur de médecine vétérinaire",
   "Professeur de dentisterie",
   "Professeur de pharmacie",
   "Professeur de médecine alternative",
   "Professeur de rééducation",
   "Professeur de kinésithérapie",
   "Professeur de psychomotricité",
   "Professeur d'orthophonie",
   "Professeur d'orthoptie",
   "Professeur d'audioprothèse",
   "Professeur d'optométrie",
   "Professeur de traduction",
   "Professeur d'interprétation",
   "Professeur de rédaction",
   "Professeur de communication",
   "Professeur de relations publiques",
   "Professeur de marketing",
   "Professeur de commerce international",
   "Professeur de gestion",
   "Professeur de ressources humaines",
   "Professeur de finances",
   "Professeur de comptabilité",
   "Professeur d'économie",
   "Professeur de droit",
   "Professeur de sciences politiques",
   "Professeur de sociologie",
   "Professeur de psychologie",
   "Professeur de sciences de l'éducation",
   "Professeur de sciences de la communication",
   "Professeur de marketing digital",
   "Professeur de commerce électronique",
   "Professeur de gestion de projet",
   "Professeur de développement personnel",
   "Professeur de leadership",
   "Professeur de négociation",
   "Professeur de vente",
   "Professeur de gestion des conflits",
   "Professeur de gestion du temps",
   "Professeur de coaching",
   "Professeur de développement professionnel",
   "Professeur de planification de carrière",
   "Professeur de langues étrangères",
   "Professeur de communication",
   "Professeur de journalisme",
   "Professeur de communication d'entreprise",
   "Professeur de relations publiques",
   "Professeur de marketing",
   "Professeur de publicité",
   "Professeur de commerce international",
   "Professeur de gestion",
   "Professeur de ressources humaines",
   "Professeur de finances",
   "Professeur de comptabilité",
   "Professeur de gestion hôtelière",
   "Professeur de tourisme",
   "Professeur de restauration",
   "Professeur de gestion de voyage",
   "Professeur de sciences politiques",
   "Professeur de développement du tourisme",
   "Professeur de gestion des événements",
   "Professeur de gestion de patrimoine",
   "Professeur de gestion immobilière",
   "Professeur de marketing sportif",
   "Professeur d'aviation",
   "Professeur de transport et logistique",
   "Professeur de gestion aéroportuaire",
   "Professeur de gestion maritime",
   "Professeur de gestion des transports publics",
   "Professeur de tourisme spatial",
   "Professeur de tourisme d'aventure",
   "Professeur de tourisme équestre",
   "Professeur de tourisme culturel",
   "Professeur de tourisme durable",
   "Professeur de tourisme de luxe",
   "Professeur de tourisme médical",
   "Professeur de tourisme religieux",
   "Professeur de tourisme gastronomique",
   "Professeur de tourisme rural",
   "Professeur de tourisme balnéaire",
   "Professeur de tourisme de montagne",
   "Professeur de tourisme de croisière",
   "Professeur de tourisme de loisirs",
   "Professeur de tourisme d'affaires",
   "Professeur de tourisme événementiel",
   "Professeur de tourisme culturel",
   "Professeur de tourisme durable",
   "Professeur de tourisme de luxe",
   "Professeur de tourisme médical",
   "Professeur de tourisme religieux",
   "Professeur de tourisme gastronomique",
   "Professeur de tourisme rural",
   "Professeur de tourisme balnéaire",
   "Professeur de tourisme de montagne",
   "Professeur de tourisme de croisière",
   "Professeur de tourisme de loisirs",
   "Professeur de tourisme d'affaires",
   "Professeur de tourisme événementiel",
   "Professeur de restauration",
   "Professeur de cuisine",
   "Professeur de pâtisserie",
   "Professeur de sommellerie",
   "Professeur de barista",
   "Professeur de mixologie",
   "Professeur de gestion hôtelière",
   "Professeur de gestion de restaurant",
   "Professeur de service à la clientèle",
   "Professeur de gestion d'événements",
   "Professeur de gestion des hôtels et resorts",
   "Professeur de gestion des spas",
   "Professeur de gestion des casinos",
   "Professeur de gestion des clubs de golf",
   "Professeur de gestion de tourisme d'aventure",
   "Professeur de gestion de tourisme culturel",
   "Professeur de gestion de tourisme durable",
   "Professeur de gestion de tourisme de luxe",
   "Professeur de gestion de tourisme médical",
   "Professeur de gestion de tourisme religieux",
   "Professeur de gestion de tourisme gastronomique",
   "Professeur de gestion de tourisme rural",
   "Professeur de gestion de tourisme balnéaire",
   "Professeur de gestion de tourisme de montagne",
   "Professeur de gestion de tourisme de croisière",
   "Professeur de gestion de tourisme de loisirs",
   "Professeur de gestion de tourisme d'affaires",
   "Professeur de gestion de tourisme événementiel",
   "Professeur de gestion de tourisme de voyage",
   "Professeur de gestion de tourisme spatial",
   "Professeur de gestion de tourisme de luxe",
   "Professeur de gestion de tourisme médical",
   "Professeur de gestion de tourisme religieux",
   "Professeur de gestion de tourisme gastronomique",
   "Professeur de gestion de tourisme rural",
   "Professeur de gestion de tourisme balnéaire",
   "Professeur de gestion de tourisme de montagne",
   "Professeur de gestion de tourisme de croisière",
   "Professeur de gestion de tourisme de loisirs",
   "Professeur de gestion de tourisme d'affaires",
   "Professeur de gestion de tourisme événementiel",
   "Professeur de gestion de tourisme de voyage",
   "Professeur de gestion de tourisme spatial",
   "Professeur de gestion de tourisme d'aventure",
   "Professeur de gestion de tourisme culturel",
   "Professeur de gestion de tourisme durable",
   "Professeur de gestion de tourisme de luxe",
   "Professeur de gestion de tourisme médical",
   "Professeur de gestion de tourisme religieux",
   "Professeur de gestion de tourisme gastronomique",
   "Professeur de gestion de tourisme rural",
   "Professeur de gestion de tourisme balnéaire",
   "Professeur de gestion de tourisme de montagne",
   "Professeur de gestion de tourisme de croisière",
   "Professeur de gestion de tourisme de loisirs",
   "Professeur de gestion de tourisme d'affaires",
   "Professeur de gestion de tourisme événementiel",
   "Professeur de gestion de tourisme de voyage",
   "Professeur de gestion de tourisme spatial",
   "Professeur de logistique",
   "Professeur de gestion des transports",
   "Professeur de gestion de la chaîne d'approvisionnement",
   "Professeur de gestion de l'entreposage",
   "Professeur de gestion des stocks",
   "Professeur de gestion des achats",
   "Professeur de gestion des approvisionnements",
   "Professeur de gestion des opérations",
   "Professeur de gestion des transports publics",
   "Professeur de gestion des transports aériens",
   "Professeur de gestion des transports maritimes",
   "Professeur de gestion des transports terrestres",
   "Professeur de gestion des transports routiers",
   "Professeur de gestion des transports ferroviaires",
   "Professeur de gestion des transports urbains",
   "Professeur de gestion des transports de marchandises",
   "Professeur de gestion des transports de passagers",
   "Professeur de gestion des transports en commun",
   "Professeur de gestion des transports internationaux",
   "Professeur de gestion des transports nationaux",
   "Professeur de gestion des transports régionaux",
   "Professeur de gestion des transports de fret",
   "Professeur de gestion des transports de voyageurs",
   "Professeur de gestion des transports routiers",
   "Professeur de gestion des transports ferroviaires"
],
"Agent_de_maitrise": [
   "Contremaître",
   "Agent de maîtrise en industrie",
   "Agent de maîtrise en bâtiment",
   "Agent de maîtrise en électromécanique",
   "Agent de maîtrise en maintenance industrielle",
   "Agent de maîtrise en génie civil",
   "Agent de maîtrise en gestion logistique",
   "Agent de maîtrise en informatique de gestion",
   "Agent de maîtrise en gestion des ressources humaines",
   "Agent de maîtrise en génie mécanique",
   "Agent de maîtrise en télécommunications",
   "Agent de maîtrise en réseau informatique",
   "Agent de maîtrise en gestion des entreprises",
   "Agent de maîtrise en comptabilité",
   "Agent de maîtrise en génie électrique"
 ],
 "agent_execution": [
   "Ouvrier agricole",
   "Manœuvre",
   "Agent de nettoyage",
   "Chauffeur",
   "Serveur/serveuse",
   "Agent de sécurité",
   "Aide-soignant(e)",
   "Secrétaire",
   "Opérateur(trice) de production",
   "Agent de maintenance",
   "Manutentionnaire",
   "Agent de restauration",
   "Gardien(ne)",
   "Agent de propreté urbaine",
   "Aide maçon",
   "Aide électricien(ne)",
   "Aide plombier",
   "Aide menuisier(ère)"
 ],
 "technicien_3eme_grade": [
   "Technicien(ne) en informatique",
   "Technicien(ne) en électronique",
   "Technicien(ne) en électromécanique",
   "Technicien(ne) en télécommunications",
   "Technicien(ne) en génie civil",
   "Technicien(ne) en génie électrique",
   "Technicien(ne) en mécanique automobile",
   "Technicien(ne) en maintenance industrielle",
   "Technicien(ne) en énergie renouvelable",
   "Technicien(ne) en climatisation et en froid",
   "Technicien(ne) en audiovisuel",
   "Technicien(ne) en automatisme industriel",
   "Technicien(ne) en laboratoire",
   "Technicien(ne) en mécatronique",
   "Technicien(ne) en topographie",
   "Technicien(ne) agricole",
   "Technicien(ne) en hygiène et sécurité au travail",
   "Technicien(ne) en génie chimique"
 ],
 "technicien_4eme_grade": [
   "Technicien(ne) spécialisé(e) en gestion des ressources humaines",
   "Technicien(ne) spécialisé(e) en commerce international",
   "Technicien(ne) spécialisé(e) en gestion logistique",
   "Technicien(ne) spécialisé(e) en informatique de gestion",
   "Technicien(ne) spécialisé(e) en génie mécanique",
   "Technicien(ne) spécialisé(e) en maintenance des systèmes électroniques",
   "Technicien(ne) spécialisé(e) en génie électromécanique"
 ],
 "technicien_superieur": [
   "Technicien(ne) supérieur(e) en informatique",
   "Technicien(ne) supérieur(e) en électronique",
   "Technicien(ne) supérieur(e) en électromécanique",
   "Technicien(ne) supérieur(e) en génie civil",
   "Technicien(ne) supérieur(e) en génie électrique",
   "Technicien(ne) supérieur(e) en maintenance industrielle",
   "Technicien(ne) supérieur(e) en mécanique automobile",
   "Technicien(ne) supérieur(e) en réseau informatique",
   "Technicien(ne) supérieur(e) en gestion des entreprises",
   "Technicien(ne) supérieur(e) en comptabilité"
 ],
 "ingenieur": [
   "Ingénieur(e) en informatique",
   "Ingénieur(e) en électronique",
   "Ingénieur(e) en électromécanique",
   "Ingénieur(e) en génie civil",
   "Ingénieur(e) en génie électrique",
   "Ingénieur(e) en mécanique",
   "Ingénieur(e) en télécommunications",
   "Ingénieur(e) en génie industriel",
   "Ingénieur(e) en génie chimique",
   "Ingénieur(e) agronome"
 ]
}
//////////////////////////
const grade= document.querySelector('#grade')
const specialite= document.querySelector('#specialite')
Object.keys(metiers).forEach(metier=>{
   const option = document.createElement("option")
   option.innerHTML=metier.replace(/_/g," ")
   grade.append(option)
})
grade.addEventListener("change",()=>{
   const options= document.querySelectorAll("#specialite option")
   options.forEach(element => {
      specialite.removeChild(element)
   });
   const dis= document.createElement("option")
   dis.innerHTML="-"
   dis.setAttribute("disabled","diasbled")
   dis.setAttribute("selected","selected")
   specialite.append(dis)
   metiers[Object.keys(metiers)[grade.selectedIndex-1]].forEach(metier=>{
      const option = document.createElement("option")
      option.innerHTML=metier
      specialite.append(option)
   })
})